### ISSUE TITLE
Current status, fdroid release

### ISSUE THREAD

**Issue by Bubu** [Frozen-Developers/android-periodic-table#14]
Hey @Lubo,

I wanted to ask what's the current status of the project. The last release has been a while but there are 308 commits since v1.1.1.

Right now this app is only available in the f-droid archive (see here for more info: https://forum.f-droid.org/t/many-old-unmaintained-apps-have-been-archived/670)

The app can be rebuild by fdroid but this a manual process, alternatively if you are planning a new release in the near future (or consider master stable eanough for at least an alpha/beta release) we could instead add this new version to fdroid.

What do you think?

**Comment by lubo** [comment]
Hi @Bubu. The project is pretty much dead. As far as I remember, master is not ready for another release. Also, I'm not a F-Droid user so I won't be taking any action. I hope you understand.

**Comment by Bubu** [comment]
Alright, thanks for the heads up!
